import {
  faEdit,
  faTrashCan,
  faSquare,
  faBell,
  faUserCircle,
  faEye,
  faEyeSlash,
  faCircleXmark,
  faFaceSmile,
  faFaceMeh,
  faFaceFrown,
} from '@fortawesome/free-regular-svg-icons';
import {
  faAddressBook,
  faAt,
  faCalendar,
  faLocationDot,
  faLock,
  faPenClip,
  faPhone,
  faShare,
  faSpa,
  faSpinner,
  faUser,
  faVenusMars,
  faCheckSquare,
  faRightFromBracket,
  faArrowLeft,
  faAngleDown,
  faAngleUp,
  faCheck,
  faX,
  faBan,
  faExclamationCircle,
  faPerson,
  faPersonDress,
  faCheckCircle,
  faPlus,
  faSearch,
  faCalendarAlt,
  faCommentDots,
  faHandshake,
  faWifi,
  faLeaf,
  faUserTie,
  faBullhorn,
  faHeadset,
  faDollar,
  faBagShopping,
  faStar,
} from '@fortawesome/free-solid-svg-icons';

const icons = {
  spinner: faSpinner,
  user: faUser,
  username: faAddressBook,
  password: faLock,
  phone: faPhone,
  email: faAt,
  date: faCalendar,
  source: faShare,
  assign: faPenClip,
  age: faSpa,
  gender: faVenusMars,
  male: faPerson,
  female: faPersonDress,
  city: faLocationDot,
  edit: faEdit,
  trash: faTrashCan,
  logout: faRightFromBracket,
  back: faArrowLeft,
  angleUp: faAngleUp,
  angleDown: faAngleDown,
  search: faSearch,
  plus: faPlus,
  square: faSquare,
  checkSquare: faCheckSquare,
  checkCircle: faCheckCircle,
  check: faCheck,
  x: faX,
  xCircle: faCircleXmark,
  ban: faBan,
  exclamationCircle: faExclamationCircle,
  wifi: faWifi,
  notifications: faBell,
  profile: faUserCircle,
  eye: faEye,
  eyeSlash: faEyeSlash,
  leaf: faLeaf,
  manager: faUserTie,
  moderator: faBullhorn,
  sales: faHeadset,
  money: faDollar,
  star: faStar,
  interest: faBagShopping,
  sentiment: {
    positive: faFaceSmile,
    neutral: faFaceMeh,
    negative: faFaceFrown,
  },
  actions: {
    call: faPhone,
    message: faCommentDots,
    meeting: faCalendarAlt,
    deal: faHandshake,
  },
};

export default icons;
